<!-- File autogenerated by the Paraglide-SvelteKit CLI - Feel free to edit -->
<script>
  import { ParaglideJS } from "@inlang/paraglide-sveltekit";
  import { i18n } from "$lib/i18n";
  import {
    availableLanguageTags,
    languageTag,
    sourceLanguageTag,
  } from "$lib/paraglide/runtime";
  import { base } from "$app/paths";
</script>

<ParaglideJS {i18n}>
  <header>
    {#each availableLanguageTags as lang}
      <a
        data-no-translate
        href={lang === sourceLanguageTag ? base : base + "/" + lang}
        hreflang={lang}
        aria-current={languageTag() === lang ? "page" : undefined}
        >{lang}
        
        </a
      >
    {/each}
  </header>
  <slot />
</ParaglideJS>

<style>
  header {
    position: fixed;
    top: 0;
    left: 50%;
    transform: translateX(-50%);

    display: flex;
    gap: 1rem;
    padding: 1rem;

    font-size: 1.5rem;
  }
  a {
    color: inherit;
    text-decoration: none;
  }

  a[aria-current="page"] {
      font-weight: bold;
  }
</style>
